<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- AspNetCore にdefault で入っている Microsoft.Extensions.Caching.Memory を利用するため -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\MyApp.Core\MyApp.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
