name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          global-json-file: "global.json"

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Check vulnerable packages
        run: dotnet list package --vulnerable --include-transitive

      - name: Check format
        run: dotnet format --verify-no-changes --no-restore --severity info

      - name: Build project
        run: dotnet build -c Release --no-restore

      - name: Test with Coverage
        run: |
          dotnet test -c Release --no-build -- \
            --coverage \
            --coverage-output-format cobertura \
            --coverage-output coverage.cobertura.xml \
            --coverage-settings coverage.settings.xml

      - name: Check Coverage Threshold
        run: |
          dotnet tool run reportgenerator \
            -reports:"TestResults/coverage.cobertura.xml" \
            -targetdir:"TestResults/html" \
            -reporttypes:Html \
            --minimumCoverageThresholds:lineCoverage=80 \
            --minimumCoverageThresholds:branchCoverage=80

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false # どこにも外部送信しない
          load: true # ローカルの docker images に登録して、この後のステップで docker run できるようにする
          tags: my-blazor-app:latest
          cache-from: type=gha # GitHub Actions Cache から読み込み
          cache-to: type=gha,mode=max # 次回のために中間レイヤーを含む全レイヤーを GitHub に保存する
